export const LOGIN = '/Login';
export const LANDING = '/';
// export const ACCOUNT = '/account';
// export const PASSWORD_FORGET = '/pw-forget';
export const NEW_PLAN = '/NewPlan';
export const NEW_INVOICE = '/NewInvoice';
export const OVERVIEW = '/Overview';
export const INVOICES = '/Invoices';
export const CLIENTS = '/Clients';